Feature view tasks for particular day
AY2223S1-CS2103T-T12-4/tp pull request #207
Opened 2022-10-19 16:41 UTC by Ramanathan0908

This PR adds the tasksOn command which lists the tasks on a particular day

2022-10-19 16:45 UTC, Ramanathan0908 commented on src/main/java/seedu/uninurse/model/task/TaskList.java
>      }
I have changed the return type to List<Tasks>, but decided to keep the method getTasks() and instead use it to return filteredTaskList, specific to TaskList

2022-10-23 09:33 UTC, izzahaj commented on docs/UserGuide.md
> +Shows a list of all tasks on a particular day
Missed a full stop.
```suggestion
Shows a list of all tasks on a particular day.
```

2022-10-23 09:35 UTC, izzahaj commented on docs/UserGuide.md
> +* `tasksOn 25-12-2022` lists the tasks on 25th december 2022
Months should start with an uppercase letter.
```suggestion
* `tasksOn 25-12-2022` lists the tasks on 25th December 2022
```

P

2022-10-23 09:37 UTC, izzahaj requested changes
LGTM except for very minor issues in the user guide. There are also merge conflicts, so I suggest resolving those first.

2022-10-24 12:33 UTC, izzahaj approved these changes
LGTM

2022-10-24 13:13 UTC, merged